game_website/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    # We'll use core as our default app, so we won't have a url prefix
    url(r'^', include('core.urls.base', namespace="core")),
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^comments/', include('game_comments.urls', namespace='game_comments')),
)

core/models.py
"""All database models for this application."""
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from stdimage.models import StdImageField
from django.core.urlresolvers import reverse

from core.managers import GameManager
from core.managers import UserManager


class MyFile(models.Model):
    game_file = models.FileField(blank=True, null=True)
    name = models.CharField(max_length=100, null=True)

    def __unicode__(self):
        return self.name


class User(AbstractBaseUser, PermissionsMixin):
    """
    User for this site.

    Requires only an email and password.
    """

    GENDER_CHOICES = (('', 'Prefer not to disclose'),
                      ('M', 'Male'),
                      ('F', 'Female'),
                      ('O', 'Other'),)
    email = models.EmailField(blank=False, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    is_staff = models.BooleanField(default=False,
                                   help_text='Designates whether the user can log into this admin '
                                             'site.')
    date_joined = models.DateTimeField(auto_now_add=True)
    birthday = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1,
                              blank=True,
                              choices=GENDER_CHOICES)
    public = models.BooleanField(default=True,
                                 help_text='Determines whether or not your profile is open to the public')

    USERNAME_FIELD = 'email'
    objects = UserManager()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    @property
    def display_name(self):
        """Return the name that should be displayed to the public"""
        if not self.public:
            return 'Anonymous'
        elif self.get_full_name():
            return self.get_full_name()
        else:
            return self.email

    @property
    def has_unread_notifications(self):
        notifications = UserNotification.objects.filter(user=self, read=False)
        return len(notifications) is not 0

    @property
    def notifications(self):
        notifications = UserNotification.objects.filter(user=self).order_by('read')[:5]
        return notifications

    def push_notification(self, description, url):
        notification = UserNotification()
        notification.user = self
        notification.description = description
        notification.redirect_url = url
        notification.save()

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def can_edit_game(self, game):
        return self in game.group.members.all()


class UserNotification(models.Model):
    redirect_url = models.URLField()
    user = models.ForeignKey(User)
    description = models.CharField(max_length=256)
    read = models.BooleanField(default=False)

    @property
    def link(self):
        return reverse('core:profile:notifications', kwargs={'notification_id': self.pk})

    def __unicode__(self):
        return self.description


class Group(models.Model):
    """Groups that can consist of Users."""

    members = models.ManyToManyField(User)
    name = models.CharField(max_length=50)

    def get_games(self):
        games = Game.objects.filter(group=self)
        return games

    def get_absolute_url(self):
        """Detail page for a group."""
        return reverse('core:groups-detail', kwargs={'pk': self.pk})

    def push_notification(self, description, url):
        for user in self.members.all():
            notification = UserNotification()
            notification.user = user
            notification.description = description
            notification.redirect_url = url
            notification.save()

    def __unicode__(self):
        return self.name


class GroupInvitation(models.Model):
    """An invitation for a group."""

    user = models.ForeignKey(User, null=False)
    group = models.ForeignKey(Group, null=False)
    inviting = models.BooleanField(null=False, default=True)

    # For the inviting field here:
    # true: this is an invation from the group to the user
    # false: this is a request from the user to join the group

    def accept(self):
        self.group.members.add(self.user)
        self.group.save()
        self.group.push_notification('A new user has joined your group!',
                                     reverse('core:groups-detail', kwargs={'pk': self.group.id}))
        self.delete()

    def decline(self):
        self.delete()

    def valid_user(self, user):
        return ((self.inviting and user == self.user) or
                (not self.inviting and user in self.group.members.all()))

    @classmethod
    def create(cls, group, user, inviting):
        invite = cls(user=user, group=group, inviting=inviting)
        invite.save()
        if inviting:
            invite.user.push_notification('A group has invited you to join.',
                                          reverse('core:invite', kwargs={'pk': invite.id}))
        else:
            invite.group.push_notification('A user has requested to join your group.',
                                           reverse('core:invite', kwargs={'pk': invite.id}))
        return invite


class GameTag(models.Model):
    """Tags to label Games."""

    value = models.CharField(max_length=50)

    def __unicode__(self):
        return self.value


class Game(models.Model):
    """Game object."""

    name = models.CharField(max_length=50)
    image = StdImageField(upload_to='game_images', null=True, blank=True,
                          variations={'thumbnail': {'width': 200, 'height': 200}})
    game_file = models.ManyToManyField(MyFile, blank=True)
    description = models.TextField(max_length=5000)
    date_published = models.DateField(auto_now_add=True)
    group = models.ForeignKey(Group, null=False)
    event_name = models.CharField(max_length=75, blank=True, default='')
    tags = models.ManyToManyField(GameTag, null=True, blank=True)
    featured = models.BooleanField(default=False)
    objects = GameManager()

    @property
    def small_description(self):
        if len(self.description) > 300:
            return self.description[:300] + '...'
        else:
            return self.description

    @property
    def average_rating(self):
        ratings = zip(*self.gamerating_set.all().values_list('value'))
        if ratings:
            ratings = ratings[0]
            return sum(ratings) / len(ratings)
        else:
            return 0

    @property
    def total_ratings(self):
        ratings = zip(*self.gamerating_set.all().values_list('value'))
        if len(ratings) != 0:
            return len(ratings[0])
        return 0

    def push_notification(self):
        if self.group:
            return self.group.push_notification(description='Somebody commented on a game of yours!',
                                                url=reverse('core:games:specific', kwargs={'game_id': self.pk}))

    def __unicode__(self):
        return self.name


class GameRating(models.Model):
    game = models.ForeignKey(Game)
    user = models.ForeignKey(User)
    value = models.FloatField(choices=(
        (.5, .5),
        (1, 1),
        (1.5, 1.5),
        (2, 2),
        (2.5, 2.5),
        (3, 3),
        (3.5, 3.5),
        (4, 4),
        (4.5, 4.5),
        (5, 5),
    ))

core/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML, Submit, Button, Fieldset
from django.forms import ModelForm, Textarea
from core.models import Game


class GameForm(ModelForm):
    class Meta:
        model = Game
        exclude = ['owner', 'date_published']
        widgets = {
            'description': Textarea(attrs={'cols': 100, 'rows': 15})
        }

    def __init__(self, *args, **kwargs):
        super(GameForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Currently Editing Game',
                'name',
                'link',
                HTML("""{% if form.image.value %}<img class="img-responsive" src="{{ MEDIA_URL }}{{ form.image.value }}">
                {% endif %}"""),
                'image',
                'description',
                'owner',
                'group',
                'event_name',
                'genre'
            ),
            FormActions(
                Submit('save', 'Save'),
                Button('cancel', 'Cancel', onclick='history.go(-1);', css_class="btn-default")
            )
        )

core/forms/games.py
"""Forms for games."""
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML, Submit, Button, Fieldset
from django import forms
from django.forms import Textarea
from core.models import Game
from core.models import MyFile
from django_select2.widgets import Select2MultipleWidget
from crispy_forms.layout import Div


class GameForm(forms.ModelForm):
    """Form for game creation and editing."""
    my_game_file = forms.FileField(required=False)
    game_version = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Game
        exclude = ['owner', 'date_published']
        widgets = {
            'description': Textarea(attrs={'cols': 100, 'rows': 5}),
            'tags': Select2MultipleWidget(),
        }

    def __init__(self, *args, **kwargs):
        """Setup the form to work with crispy_forms."""
        super(GameForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'game-form'
        self.helper.layout = Layout(
            Fieldset(
                '{{ heading }}',
                'name',
                'group',
                'description',
                HTML("""{% if form.image.value %}<img class="img-responsive" src="{{ MEDIA_URL }}{{ form.image.value }}">
                {% endif %}"""),
                'tags',
                'image',
                'event_name',
                Div(
                    HTML('<p class="blockLabel">Upload a file for this game.</p>'),
                    'game_version',
                    'my_game_file',
                    HTML("""\
                    {% if game.game_file %}
                    <div class="top10">
                        <h2 class="files-header">Current Game Files</h2>
                        <ul class="list-group lead">
                            {% for file in game.game_file.all %}
                                <li class="list-group-item"><a href="{{file}}" download> {{file.name}}</a></li>
                            {% empty %}
                                <li class="list-group-item">No files found</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}"""),
                    css_class="form-upload",
                ),
            ),
            FormActions(
                Submit('submit', 'Submit'),
                Button('cancel', 'Cancel', onclick='history.go(-1);', css_class="btn-default")
            )
        )

    def save(self, commit=True):
        game = super(GameForm, self).save(commit=False)
        game.save()

        # Save our tags
        tags = self.cleaned_data.get('tags')
        if tags:
            game.tags = tags
            game.save()

        # Save the game files
        my_file = self.cleaned_data.get('my_game_file')
        if my_file:
            my_file = MyFile(name=self.cleaned_data['game_version'], game_file=my_file)
            my_file.save()
            game.game_file.add(my_file)
        return game

    def clean_game_version(self):
        version = self.cleaned_data.get('game_version')
        game_file = self.cleaned_data.get('my_game_file')
        if game_file and not version:
            raise forms.ValidationError('Uploading a file requires a version.', code='invalid')
        elif not game_file and version:
            raise forms.ValidationError('Versioning requires a game file.', code='invalid')
        else:
            return version

core/views/base.py
"""Base views and view utilities."""
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


class LoginRequiredMixin(object):

    """Ensures that user must be authenticated in order to access view."""

    @classmethod
    def as_view(cls, **initkwargs):
        """Make views that inherit this require login."""
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


class Home(View):

    """Default index page handler."""

    def get(self, request, *args, **kwargs):
        """Simply render the index page."""
        return render(request, "index.html")

core/views/notifications.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from core.models import UserNotification


@login_required
def base(request, notification_id):
    """URL that marks the notification read then redirects"""
    notification = UserNotification.objects.get(pk=notification_id)
    if int(notification.user.pk) != int(request.user.pk):
        response = HttpResponse(status=403)
    else:
        response = HttpResponseRedirect(notification.redirect_url)
        notification.read = True
        notification.save()
    return response

core/templates/user/edit_profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}

{% endblock %}

{% block title %}
    Edit Profile
{% endblock %}


{% block content %}
    {% load crispy_forms_tags %}
    {% crispy form %}
{% endblock %}

core/templates/user/group.html
{% extends "base.html" %}

{% block title %}{{ group.name }}{% endblock %}

{% block content %}
    <a href="{% url 'core:groups' %}">&laquo; Back To Groups Page</a>
    <div class="page-header">
        <h1>Group: {{ group.name }}</h1>
    </div>
    <h4>Group Members</h4>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Member Name</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for member in group.members.all %}
            <tr {% if member.email == user.email %}class="success"{% endif %}>
                <td>{{ member.display_name }}</td>
                <td>
                    <a href="{% url 'core:profile:user-profile' member.pk %}" class="btn btn-sm btn-primary"><i
                            class="fa fa-search fa-fw"></i> View</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="2">No members found.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h4>Group Games</h4>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Image</th>
                <th>Game</th>
                <th>Description</th>
                <th>Group</th>
                <th>Link</th>
            </tr>
            </thead>
            <tbody>
            {% for game in games %}
                <tr>
                    <td class="text-center">
                        {% if game.image %}
                            <img src="{{ game.image.thumbnail.url }}"
                                 class="img-responsive img-rounded"
                                 style="display: inline-block;">
                        {% else %}
                            <i class='fa fa-gamepad fa-5x'></i>
                        {% endif %}
                    </td>
                    <td><strong class='text-capitalized'>{{ game.name }}</strong></td>
                    <td>{{ game.small_description }}</td>
                    <td>{{ game.group }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'core:games:specific' game_id=game.pk %}">View Game</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">No Games Found.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% if in_group %}
        <a href="{% url 'core:groups-leave' group.pk %}" class="btn btn-sm btn-danger"><i class="fa fa-minus fa-fw"></i>
            Leave Group</a>
    {% elif request_sent %}
        <p><em>Join request is pending...</em></p>
    {% elif not request_sent %}
        <a href="{% url 'core:groups-join' group.pk %}" class="btn btn-sm btn-success"><i class="fa fa-plus fa-fw"></i>
            Request to Join Group</a>
    {% endif %}
{% endblock %}

core/templates/user/groups.html
{% extends "base.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ page_title }}</h1>
    </div>

    <div>
    <a href="{% url 'core:groups-new' %}" class="btn btn-sm btn-success"><i class="fa fa-plus-circle fa-fw"></i> New
        Group</a>
    </div>
    <table class="top10 table table-bordered table-striped">
        <thead>
        <tr>
            <th>Group Name</th>
            <th>Members</th>
            <th>Games</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for group in object_list %}
            <tr>
                <td>{{ group.name }}</td>
                <td>{{ group.members.all | length }}</td>
                <td>{{ group.game_set.all | length }}</td>
                <td>
                    <a href="{% url 'core:groups-detail' group.pk %}" class="btn btn-sm btn-primary"><i
                            class="fa fa-search fa-fw"></i> View</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">No User Groups found.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

core/templates/user/invitation.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Group Invitation{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Group Invitation</h1>
    </div>
    <div class="lead">
        {% if not viewable %}
            <p>
            You do not have permission to view this invitation. Click <a href="{% url 'core:home' %}">here</a> to return home.
            </p>
        {% else %}
            <p>
            {% if invite.inviting and is_user %}
                Group "<a href="{% url 'core:groups-detail' pk=invite.user.id %}">{{invite.group}}</a>" would like you to join their group.
            {% else %}
                User "<a href="{% url 'core:profile:user-profile' pk=invite.user.id %}">{{invite.user}}</a>" would like to join your group 
                    "<a href="{% url 'core:groups-detail' pk=invite.user.id %}">{{invite.group}}</a>".</p>
            {% endif %}
            </p>
            <div>
                <button id="acceptBtn" class="btn btn-success"><i class="fa fa-check"></i> Accept</button>
                <button id="declineBtn" class="btn btn-danger"><i class="fa fa-times"></i> Decline</button>
            </div>
        {% endif %}
    </div>

<script type="text/javascript" src="{% static "js/invite.js" %}"></script>
{% endblock %}

core/templates/user/new_group.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create a Group{% endblock %}

{% block content %}
  <div class="page-header">
    <h1>Create Group</h1>
  </div>

  <form method="post" action="{% url 'core:groups-new' %}">{% csrf_token %}
    {{ form | crispy }}
    <div>
      <button type="submit" class="btn btn-success">Create</button>
    </div>
   </form>

{% endblock %}

core/templates/user/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Profile{% endblock %}
{% block content %}
    <div class="page-header" style="border: none">
        <h1>Profile: {{ object.display_name }}</h1>
    </div>
    <div class="row">
        <div class="col-md-3" style="border-right: solid 1px #eee; border-top: solid 1px #eee">
            <h4 style="padding-bottom: 5px; padding-top: 5px">Personal</h4>
            <img src="http://placekitten.com/g/200/300" class="img-responsive img-rounded" alt="Responsive image">
            {% if object.public %}
                <dl class="dl" style="margin-top: 20px">
                    {% if object.fist_name or object.last_name %}
                        <dt>Name</dt>
                        <dd>{{ object.display_name }}</dd>
                    {% endif %}
                    {% if object.gender %}
                        <dt>Gender</dt>
                        <dd>{{ object.gender }}</dd>
                    {% endif %}
                    {% if object.birthday %}
                        <dt>Birthday</dt>
                        <dd>{{ object.birthday }}</dd>
                    {% endif %}
                    <dt>Date Joined</dt>
                    <dd>{{ object.date_joined }}</dd>
                    <dt>Contact</dt>
                    <dd>{{ object.email }}</dd>
                </dl>
            {% else %}
                <p>This user's information is hidden</p>
            {% endif %}

            {% if show_edit %}
                <a class="btn btn-default btn-xs" role="button" href="{% url 'core:profile:edit' %}">
                    Edit Profile
                </a>
                <a class="btn btn-default btn-xs" role="button" href="{% url 'core:profile:password_change' %}">
                    Change Password
                </a>
            {% endif %}
        </div>
        <div class="col-md-9" style="border-top: solid 1px #eee; padding-top: 5px">
            <h4>Games</h4>

            <div class="top10">
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Image</th>
                        <th>Game</th>
                        <th>Description</th>
                        <th>Link</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for game in games_list %}
                        <tr>
                            <td class="text-center">
                                {% if game.image %}
                                    <img src="{{ game.image.thumbnail.url }}"
                                         class="img-responsive img-rounded"
                                         style="display: inline-block;">
                                {% else %}
                                    <i class='fa fa-gamepad fa-5x'></i>
                                {% endif %}
                            </td>
                            <td><strong class='text-capitalized'>{{ game.name }}</strong></td>
                            <td>{{ game.small_description }}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'core:games:specific' game_id=game.pk %}">View
                                    Game</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="4">No Games Found.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% if invite_groups %}
    <div class="row" style="border-top: solid 1px #eee; padding-top: 5px">
        <label>Invite This User to a Group</label>

        <input id="userId" type="hidden" value="{{object.id}}"/>
        <select id="groupSelect" class="form-control">
            {% for group in invite_groups %}
            <option value="{{group.id}}">{{group}}</option>
            {% endfor %}
        </select>
        <div class="top10">
        <button id="inviteBtn" class="btn btn-primary"><i class="fa fa-envelope"></i> Invite</button>
        </div>
    </div>

    {% endif %}

<script type="text/javascript" src="{% static "js/profile.js" %}"></script>
{% endblock %}